import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Providers from "@/Provider/Providers";
import AppLayout from "./AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-shop",
  description: "Generated by Rofikul Islam Resan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
